name: Android CI

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  codecov:
    name: Code coverage
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Generate coverage reports
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          script: ./gradlew connectedAndroidTest

      - name: Codecov
        run: bash <(curl -s https://codecov.io/bash)
