name: Android CI

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Run unit tests
        run: ./gradlew test

  instrumented-tests:
    name: Instrumented Tests
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run instrumented tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: google_apis
          script: ./gradlew connectedAndroidTest

      - name: Upload coverage reports
        run: bash <(curl -s https://codecov.io/bash)
